version: "3.2"

services:
  go-api:
    container_name: go-api
    image: golang:alpine
    hostname: api
    restart: always
    privileged: true
    user: root
    ports:
      - 40839:40839
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
